<Project Sdk="Microsoft.NET.Sdk">
    <!-- BepInEx Properties -->
    <PropertyGroup>
        <AssemblyName>me.loaforc.soundapi.patcher</AssemblyName>
        <Product>loaforcsSoundAPI.Patcher</Product>
    </PropertyGroup>

    <!-- Project Properties -->
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <RootNamespace>loaforcsSoundAPI.Patcher</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <!-- Embed Debug Symbols for Easier Debugging -->
    <PropertyGroup>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>
        <!--
        Trim the project path to prevent players from potentially
        viewing Private Information in stack traces.
        -->
        <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
    </PropertyGroup>

    <!-- Primary Package References -->
    <ItemGroup>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="BepInEx.Core" Version="5.*" PrivateAssets="all" />
    </ItemGroup>
</Project>